### ISSUE TITLE
Closing the search-bar should clean the results

### ISSUE THREAD

**Issue by dfosco** [vtex-apps/search-bar#7]
Currently they remain saved and next time you open it they're still there — that's because the component is not being removed from the page, only hidden with CSS. 

We should do this better in the future, but for now cleaning up the results after clicking will do.

**Comment by brenoc** [comment]
Tried to replicate, but the error didn't occur.

**Comment by brenoc** [comment]
Closing this issue for now. If you see this happening again we reopen the issue.
